#
# continuous integration workflow
#
name: build repo

on:
 push:
    branches: [ master]
 pull_request:
    branches: [ master]
 workflow_dispatch:
    branches: [ master]

jobs:
  build_jetson_bionic_noetic:
    runs-on: ubuntu-18.04
    name: build repo under ROS1 noetic from source on jetson/bionic
#    container:
#      image: dustynv/ros:noetic-ros-base-l4t-r34.1.1
    steps:
      - uses: actions/checkout@v3
        name: check out github repo
        with:
          path: src/metavision_ros_driver
          fetch-depth: 0
      - uses: berndpfrommer/run-on-arch-action@v2
        name: compile from source
        with:
          arch: armv7
          distro: ubuntu18.04
          run:  |
            ./src/metavision_ros_driver/.github/scripts/build_ros1.bash
#  build_focal_ros2:
#    runs-on: ubuntu-20.04
#    container:
#      image: berndpfrommer/focal_noetic_galactic_metavision
#    name: build repo under ROS2 from source on focal
#    steps:
#      - name: check out github repo
#        uses: actions/checkout@v3
#        with:
#          path: src/metavision_ros_driver
#          fetch-depth: 0
#      - name: compile from source
#        run: ./src/metavision_ros_driver/.github/scripts/build_ros2.bash
#  build_focal_ros2:
#    runs-on: ubuntu-20.04
#    container:
#      image: berndpfrommer/focal_noetic_galactic_metavision
#    name: build repo under ROS2 from source on focal
#    steps:
#      - name: check out github repo
#        uses: actions/checkout@v3
#        with:
#          path: src/metavision_ros_driver
#          fetch-depth: 0
#      - name: compile from source
#        run: ./src/metavision_ros_driver/.github/scripts/build_ros2.bash
  
